### ISSUE TITLE
how to implement it to 2d case

### ISSUE THREAD

**Issue by datseismo** [chenyk1990/passive_imaging#1]
Can this software be useful for 2d case? If so can you please suggest the correct way to do it.Thanks in advance.

**Comment by chenyk1990** [comment]
It should be, but I need to prepare an example. There is an existing 2D
version, which is much simpler. I need to find it out and share it with
you.

datseismo ***@***.***> 于2021年12月12日周日 11:54写道：

**Comment by chenyk1990** [comment]
Here is the 2D example.

datseismo ***@***.***> 于2021年12月12日周日 11:54写道：

**Comment by chenyk1990** [comment]
https://github.com/chenyk1990/reproducible_research/tree/master/nonMada/microtri2d 2D example

**Comment by datseismo** [comment]
I got you point  @chenyk1990. I want to implement this programme to the 2d data attached https://i.fluffy.cc/6464gPqZzH8JhZb76JPdB6GnpKV0D7mb.html   Can you please help me doing this, i want to set the velocity model as it is given in   https://github.com/chenyk1990/reproducible_research/tree/master/nonMada/microtri2d. Thanks in advance.

**Comment by chenyk1990** [comment]
Sure.

Setting a velocity model is easy, but I at least need to know some basics of this
test dataset. For example, how it is formulated? what's the background of
it? what's the target of this test? etc.. Some references of yours or related
works are helpful.

datseismo ***@***.***> 于2021年12月13日周一 11:56写道：

**Comment by datseismo** [comment]
Target is to imaging the microseismic source directly from the 2d seismic data and here data is generated using scalo_CAE.

**Comment by chenyk1990** [comment]
That would be easy. Omar (cc'ed) will prepare a 2D imaging example for you.

datseismo ***@***.***> 于2021年12月13日周一 12:07写道：

**Comment by datseismo** [comment]
ok...i will look-forward to it.

**Comment by datseismo** [comment]
Dear @chenyk1990, can you please let me know when Omar(cc'ed) will prepare a 2D example.

**Comment by chenyk1990** [comment]
When it is ready, I will let you know. Omar just went back to Egypt, needs
time to set up his workstation.

**Comment by datseismo** [comment]
Thanks...

**Comment by datseismo** [comment]
Hii Dear Chen, can you please let me know when the package will be updated ( i requested before).

Additionally, can you suggest how to create a 1d velocity model and generate seismic data using it in Madagascar.

I think this part of the programme you provided creates 2d velocity model not 1d velocity model, 

Flow('top',None,'spike n1=80 n2=115 d1=7.5 d2=7.5 mag=2100')
Flow('mid',None,'spike n1=80 n2=115 d1=7.5 d2=7.5 mag=2500')
Flow('bot',None,'spike n1=80 n2=115 d1=7.5 d2=7.5 mag=1800')
Flow('vel','top mid bot','cat axis=1 ${SOURCES[1:2]} | smooth rect1=3 |window f1=30 n1=125|put o1=0 | put d2=%g'%d2).

Thanks in advance.

**Comment by chenyk1990** [comment]
Omar will hopefully be able to provide you with an example for his paper
"Automatic waveform-based source-location imaging using deep learning
extracted microseismic signals" since next Sunday.

"Additionally, can you suggest how to create a 1d velocity model and
generate seismic data using it in Madagascar." I don't know why you need a
1D model. Could you please explain?

datseismo ***@***.***> 于2021年12月24日周五 07:10写道：

**Comment by datseismo** [comment]
Dear Chen, My seismic data are generated using 1d velocity model and arranged the data in the 2d fashion and i want to implement rtm for the 2d data sets using my velocity model which is 1d.

Or Does the rtm  run only with 2d/3d velocity model?..Thanks.

**Comment by chenyk1990** [comment]
Just choose one trace in the 2d vel then you will have a 1d vel. Using
sfwindow<vel2.rsf n2=1 >vel1.rsf

**Comment by datseismo** [comment]
You mean first i have to generate 2d velocity model using 
Flow('top',None,'spike n1=80 n2=115 d1=7.5 d2=7.5 mag=2100')
Flow('mid',None,'spike n1=80 n2=115 d1=7.5 d2=7.5 mag=2500')
Flow('bot',None,'spike n1=80 n2=115 d1=7.5 d2=7.5 mag=1800')
Flow('vel','top mid bot','cat axis=1 ${SOURCES[1:2]} | smooth rect1=3 |window f1=30 n1=125|put o1=0 | put d2=%g'%d2).

After that i have to do sfwindow<vel.rsf n2=1 > vel1.rsf

**Comment by chenyk1990** [comment]
Yes, correct. It is simplest way.

**Comment by datseismo** [comment]
Dear Chen sir, I tried this programme with 1d model(sfwindow) as you suggested and successfully run up to the step plotting the velocity model. Afterwords I am getting error on generating data and so....

Errors:
mod2d.exe: Using pseudo-spectral...
mod2d.exe: Forward modeling
mod2d.exe: build/api/c/alloc.c: cannot allocate 18446744073709551144 bytes: Cannot allocate memory
scons: *** [data0.rsf] Error 1
scons: building terminated because of errors.


I think somewhere I am unable to recognize the error as i am new to the Madagascar programming, so it would be very nice if you can suggest a solution for running the example code for 1d model.
Thank you.

**Comment by chenyk1990** [comment]
Sure, no problem.

But I get more confused about your goal. Let me understand what you want.
Please explain clearly what you really want to model.

1. Explain why you want a 1D vel. I can't get why (1D vel is needed). You
can suggest a reference or paper or a research proposal for me so that I
know the background of your problem.

2. What you want is not related to the 3D imaging package, it is related to
basic programming of seismic modeling, or basic use of Madagascar, so,
there is no need to ask questions this way. It is not efficient. Instead,
you can directly contact me by email ***@***.***

I believe what you want is easy, but I just need what you really want.

Best regards,
Yangkang Chen






datseismo ***@***.***> 于2021年12月25日周六 08:03写道：

**Comment by datseismo** [comment]
Sorry for asking the questions here...Thanks.
